"""AI-powered file analysis - Heuristic + Optional OpenAI GPT"""

import os
from src.config import settings


# AI Analysis Constants
_AI_IMPORTANT_EXTS = {
    ".c", ".h", ".cpp", ".hpp", ".cs", ".py", ".java",
    ".xml", ".arxml", ".cfg", ".mk", ".mak", ".cmake",
    ".json", ".yaml", ".yml", ".ini", ".properties",
    ".bat", ".cmd", ".sh",
}
_AI_GENERATED_MARKERS  = ["generated", "auto-generated", "do not edit", "autogenerated"]
_AI_DEPRECATED_MARKERS = ["deprecated", "obsolete", "legacy", "unused", "todo: remove"]
_AI_IMPORTANT_MARKERS  = ["copyright", "license", "version", "author", "@brief", "@file",
                           "important", "critical", "required"]


def _read_head(path, max_lines=60):
    """Read up to max_lines of text from a file for heuristic analysis."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            return "".join(fh.readline() for _ in range(max_lines)).lower()
    except Exception:
        return ""


def _score_file(path, lines):
    """
    Return a numeric score for a file based on heuristics.
    Higher = more likely the version to keep.
    """
    if not path or not os.path.isfile(path):
        return 0
    score = 0
    ext = os.path.splitext(path)[1].lower()
    head = _read_head(path)

    # Prefer source-code / config files over temp/log files
    if ext in _AI_IMPORTANT_EXTS:
        score += 20
    elif ext in {".log", ".tmp", ".bak", ".orig", ".swp"}:
        score -= 20

    # Auto-generated files are lower priority (the generator will recreate them)
    if any(m in head for m in _AI_GENERATED_MARKERS):
        score -= 15

    # Deprecated / legacy markers reduce priority
    if any(m in head for m in _AI_DEPRECATED_MARKERS):
        score -= 25

    # Important content markers increase priority
    if any(m in head for m in _AI_IMPORTANT_MARKERS):
        score += 15

    # Larger files usually carry more content / work done
    score += min(lines, 2000) // 40

    # File size on disk (catch binary files)
    try:
        score += min(os.path.getsize(path), 200_000) // 10_000
    except Exception:
        pass

    return score


def ai_analyze_file(path1, path2, status, lines1, lines2, openai_key=""):
    """
    Heuristic + optional AI analysis of which file version to keep.
    Returns a detailed recommendation string.
    
    Args:
        path1: Path to file in folder 1 (Platform/Baseline)
        path2: Path to file in folder 2 (Project/Target)
        status: Comparison status string
        lines1: Line count in file 1
        lines2: Line count in file 2
        openai_key: Optional OpenAI API key for enhanced analysis
        
    Returns:
        str: Formatted AI recommendation with confidence level
    """
    ext = os.path.splitext(path1 or path2 or "")[1].lower()
    fname = os.path.basename(path1 or path2 or "")

    # ── Heuristic analysis ────────────────────────────────────────────────────
    lines = []
    verdict = ""
    confidence = ""

    if status == "Only in Platform":
        head = _read_head(path1)
        is_generated  = any(m in head for m in _AI_GENERATED_MARKERS)
        is_deprecated = any(m in head for m in _AI_DEPRECATED_MARKERS)
        is_important  = any(m in head for m in _AI_IMPORTANT_MARKERS) or ext in _AI_IMPORTANT_EXTS

        if is_deprecated:
            verdict = "DO NOT COPY — file appears deprecated/obsolete"
            confidence = "High"
            lines += [
                f"✖ File '{fname}' contains deprecation markers.",
                "  It is likely intentionally absent from Project.",
                "  Recommendation: LEAVE IT only in Platform, do not migrate.",
            ]
        elif is_generated:
            verdict = "LOW PRIORITY — auto-generated file"
            confidence = "Medium"
            lines += [
                f"ℹ File '{fname}' appears to be auto-generated.",
                "  The build system will recreate it in Project if needed.",
                "  Recommendation: Skip migration unless you confirmed it is hand-edited.",
            ]
        elif is_important:
            verdict = "COPY Platform → Project — likely needed in target"
            confidence = "High"
            lines += [
                f"✔ File '{fname}' ({ext}) contains important markers (copyright, version, @brief ...).",
                f"  It has {lines1} lines and looks like meaningful source code/config.",
                "  Recommendation: Copy this file to Project — it was probably missed during migration.",
            ]
        else:
            verdict = "REVIEW BEFORE COPYING"
            confidence = "Low"
            lines += [
                f"⚠ File '{fname}' exists only in Platform ({lines1} lines, type: {ext or 'unknown'}).",
                "  Could not determine automatically whether it is needed in Project.",
                "  Recommendation: Open the file, review its purpose, then decide.",
            ]

    elif status == "Only in Project":
        head = _read_head(path2)
        is_generated  = any(m in head for m in _AI_GENERATED_MARKERS)
        is_important  = any(m in head for m in _AI_IMPORTANT_MARKERS) or ext in _AI_IMPORTANT_EXTS

        if is_generated:
            verdict = "LOW PRIORITY — auto-generated in target"
            confidence = "Medium"
            lines += [
                f"ℹ File '{fname}' was auto-generated by the new build/tool in Project.",
                "  Platform does not need it — the generator was not present there.",
                "  Recommendation: Keep it in Folder 2 only; no action for Folder 1.",
            ]
        elif is_important:
            verdict = "KEEP IN F2 — new meaningful addition"
            confidence = "High"
            lines += [
                f"✔ File '{fname}' ({ext}) is a NEW file in Folder 2 ({lines2} lines).",
                "  It contains important content markers and looks like hand-crafted work.",
                "  Recommendation: Keep it in Folder 2. Consider back-porting to Folder 1 if needed.",
            ]
        else:
            verdict = "REVIEW — new file of unknown purpose"
            confidence = "Low"
            lines += [
                f"⚠ New file '{fname}' ({lines2} lines, {ext or 'unknown'}) exists only in Project.",
                "  Cannot determine automatically whether it is hand-crafted or auto-generated.",
                "  Recommendation: Open and review before deciding.",
            ]

    elif status in ("Modified", "Different", "Comments update only"):
        s1 = _score_file(path1, lines1)
        s2 = _score_file(path2, lines2)
        delta = lines2 - lines1
        head1 = _read_head(path1)
        head2 = _read_head(path2)
        dep1  = any(m in head1 for m in _AI_DEPRECATED_MARKERS)
        dep2  = any(m in head2 for m in _AI_DEPRECATED_MARKERS)

        if dep1 and not dep2:
            verdict = "PREFER F2 — baseline has deprecation markers"
            confidence = "High"
            lines += [
                "✔ Folder 1 version contains deprecation/legacy markers; Folder 2 does not.",
                "  Recommendation: Trust Folder 2 (target) as the canonical version.",
            ]
        elif dep2 and not dep1:
            verdict = "PREFER F1 — target has deprecation markers"
            confidence = "High"
            lines += [
                "✔ Folder 2 version contains deprecation markers; Folder 1 does not.",
                "  Recommendation: Investigate why the target version was deprecated.",
            ]
        elif status == "Comments update only":
            verdict = "PREFER F2 — only comments differ, keep the newer description"
            confidence = "High"
            lines += [
                "✔ Only comments changed — code logic is identical.",
                "  Folder 2 has updated comments/documentation.",
                "  Recommendation: Keep Folder 2 version (more up-to-date comments).",
            ]
        elif delta > 50:
            verdict = f"PREFER F2 — significantly larger (+{delta} lines)"
            confidence = "Medium"
            lines += [
                f"✔ Folder 2 version is {delta} lines larger ({lines1} → {lines2}).",
                "  This suggests new features or expanded implementation were added.",
                "  Recommendation: Use Folder 2; cherry-pick any Folder 1-only logic if needed.",
            ]
        elif delta < -50:
            verdict = f"PREFER F1 — Folder 2 is shorter by {-delta} lines (possible truncation?)"
            confidence = "Medium"
            lines += [
                f"⚠ Folder 2 version is {-delta} lines SHORTER ({lines1} → {lines2}).",
                "  Code may have been accidentally removed or the file was partially migrated.",
                "  Recommendation: Review the diff carefully before accepting Folder 2.",
            ]
        elif s2 >= s1:
            verdict = "PREFER F2 (target) — heuristic score favors target version"
            confidence = "Medium"
            lines += [
                f"✔ Both versions are similar in size ({lines1} vs {lines2} lines).",
                "  Heuristic analysis slightly favors Folder 2 (target/newer).",
                "  Recommendation: Keep Folder 2. View the diff to verify nothing was lost.",
            ]
        else:
            verdict = "PREFER F1 (baseline) — heuristic score favors baseline version"
            confidence = "Medium"
            lines += [
                f"⚠ Both versions similar in size ({lines1} vs {lines2} lines).",
                "  Heuristic analysis slightly favors Folder 1 (baseline).",
                "  Recommendation: Manually review the diff to confirm.",
            ]
    else:
        return "AI analysis not applicable for status: " + status

    heuristic_result = "\n".join(lines)

    # ── Optional OpenAI enhancement ───────────────────────────────────────────
    openai_result = ""
    if openai_key and openai_key.strip().startswith("sk-"):
        try:
            import urllib.request
            import json as _json
            # Build a compact diff summary to send (max ~800 chars each side)
            def _snippet(p, max_c=800):
                if not p or not os.path.isfile(p):
                    return "(not available)"
                try:
                    with open(p, "r", encoding="utf-8", errors="replace") as fh:
                        content = fh.read(max_c)
                    return content + ("..." if os.path.getsize(p) > max_c else "")
                except Exception:
                    return "(unreadable)"

            snip1 = _snippet(path1)
            snip2 = _snippet(path2)
            prompt = (
                f"You are a software migration expert. Compare these two versions of a file "
                f"named '{fname}' and decide which version to keep.\n"
                f"Comparison status: {status}\n"
                f"Lines in F1 (baseline): {lines1}\n"
                f"Lines in F2 (target): {lines2}\n\n"
                f"F1 content snippet:\n```\n{snip1}\n```\n\n"
                f"F2 content snippet:\n```\n{snip2}\n```\n\n"
                "In 3-5 sentences: which version should be kept and why?"
            )
            payload = _json.dumps({
                "model": "gpt-4o-mini",
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 300,
                "temperature": 0.3,
            }).encode()
            req = urllib.request.Request(
                "https://api.openai.com/v1/chat/completions",
                data=payload,
                headers={
                    "Authorization": f"Bearer {openai_key.strip()}",
                    "Content-Type": "application/json",
                },
            )
            with urllib.request.urlopen(req, timeout=20) as resp:
                data = _json.loads(resp.read())
            openai_result = data["choices"][0]["message"]["content"].strip()
        except Exception as ex:
            openai_result = f"(OpenAI call failed: {ex})"

    # ── Compose final output ──────────────────────────────────────────────────
    out = []
    out.append(f"✨ AI RECOMMENDATION  [Confidence: {confidence}]")
    out.append(f"   ➤ {verdict}")
    out.append("")
    out.append("▶ Heuristic Analysis:")
    out.extend(["  " + l for l in heuristic_result.splitlines()])
    if openai_result:
        out.append("")
        out.append("▶ GPT-4o-mini Analysis:")
        for l in openai_result.splitlines():
            out.append("  " + l)
    return "\n".join(out)
